development:
  adapter: postgresql
  encoding: unicode
  database: baseapp_development
  pool: 5
  username: CvK
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: baseapp_test
  pool: 5
  username: CvK
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: baseapp_test
  pool: 5
  username: CvK
  password: